initial_quaternion: [0.0, 0.0, 0.0, 1.0]

x_axis_period_s: 1200.0
x_axis_amplitude_dps: 0.1
x_axis_shift_deg: 0.0

y_axis_period_s: 900.0
y_axis_amplitude_dps: 0.1
y_axis_shift_deg: 90.0

z_axis_period_s: 1500.0
z_axis_amplitude_dps: 0.1
z_axis_shift_deg: 0.0