angle_random_walk_deg_1_sigma: 1.8e-5
turn_on_rate_bias_deg_1_sigma: 0.002777 # 10.0 deg/hr
rate_random_walk_deg_1_sigma: 1.8e-8
scale_factor_ppm_1_sigma: 100000
misalignment_deg_1_sigma: 1.0
q_body_to_gyro: [0.0, 0.0, 0.0, 1.0]