name: Personal Project Pipeline

on:
  push:
    branches:
      - '**'   # Runs on push to any branch

permissions:
  actions: write

jobs:
  # --------------------------------------
  # Create placeholder
  # --------------------------------------
  placeholder_job:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Do nothing
        shell: bash
        run: |
          echo